week 4
kmandalinic/sbss-km pull request #4
Opened 2021-08-17 08:19 UTC by kmandalinic

2021-08-17 20:08 UTC, gobonja requested changes
Pozdrav,

Ovdje možeš naći primjer što ide u koji layer: https://medium.com/stackavenue/why-to-use-service-layer-in-spring-mvc-5f4fc52643c0

Ako što zapne slobodno pitaj.

2021-08-17 20:08 UTC, gobonja commented on src/main/java/com/agency04/sbss/pizza/repository/CustomerDetailsRepository.java
> +
fali anotacija @Repository

2021-08-17 20:08 UTC, gobonja commented on src/main/java/com/agency04/sbss/pizza/controller/PizzaDeliveryController.java
> +        }
ova cijela logika bi se trebala nalaziti u servisu, isto vrijedi za ostala mjesta u controlleru je logika spremanja nije u servisu

2021-08-18 10:16 UTC, kmandalinic commented on src/main/java/com/agency04/sbss/pizza/controller/PizzaDeliveryController.java
> +        }
Popravila :) nadam se da je sad ok

2021-08-18 10:43 UTC, merged